import { Inter, Pangolin } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const pangolin = Pangolin({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-pangolin",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${pangolin.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
